BDI-15|Mohan|Add| Conditional exit based on trigger result

diff --git a/.github/workflows/ci-v0.94.yml b/.github/workflows/ci-v0.94.yml
--- a/.github/workflows/ci-v0.94.yml
+++ b/.github/workflows/ci-v0.94.yml
@@ -18,4 +18,11 @@ jobs:
         env:
           REPOSITORY_NAME: ${{ matrix.dependent-repos }}
         run : |
-              curl -X POST -H "Accept: application/vnd.github.v3+json" -H 'authorization: Bearer ${{ secrets.WORKFLOW_TRIGGER_TOKEN }}' https://api.github.com/repos/${ORG_NAME}/${REPOSITORY_NAME}/dispatches -d '{"event_type":"${EVENT_TYPE}"}'
+              trigger_result=$(curl -s -o trigger_response.txt -w "%{http_code}" -X POST -H "Accept: application/vnd.github.v3+json" -H 'authorization: Bearer ${{ secrets.WORKFLOW_TRIGGER_TOKEN }}' https://api.github.com/repos/$\{ORG_NAME\}/$\{REPOSITORY_NAME\}/dispatches -d '{"event_type":"${EVENT_TYPE}"}')
+              if [ $trigger_result == 204 ];then
+                echo "Trigger to $REPOSITORY_NAME Success"
+              else
+                echo "Trigger to $REPOSITORY_NAME Failed"
+                cat trigger_response.txt
+                exit 1
+              fi
